//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Admin.Resources.DisplayModelResource", typeof(DisplayModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar a senha.
        /// </summary>
        public static string AlterarSenha {
            get {
                return ResourceManager.GetString("AlterarSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assunto.
        /// </summary>
        public static string Assunto {
            get {
                return ResourceManager.GetString("Assunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação da nova senha.
        /// </summary>
        public static string ConfirmarNovaSenha {
            get {
                return ResourceManager.GetString("ConfirmarNovaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteúdo Chave.
        /// </summary>
        public static string ConteudoChave {
            get {
                return ResourceManager.GetString("ConteudoChave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Criação.
        /// </summary>
        public static string DataCriacao {
            get {
                return ResourceManager.GetString("DataCriacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Final.
        /// </summary>
        public static string DataFim {
            get {
                return ResourceManager.GetString("DataFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Final.
        /// </summary>
        public static string DataFinal {
            get {
                return ResourceManager.GetString("DataFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Inicial.
        /// </summary>
        public static string DataInicial {
            get {
                return ResourceManager.GetString("DataInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Inicial.
        /// </summary>
        public static string DataInicio {
            get {
                return ResourceManager.GetString("DataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Limite.
        /// </summary>
        public static string DataLimite {
            get {
                return ResourceManager.GetString("DataLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Descricao {
            get {
                return ResourceManager.GetString("Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição Complemento.
        /// </summary>
        public static string DescricaoComplemento {
            get {
                return ResourceManager.GetString("DescricaoComplemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição Curta.
        /// </summary>
        public static string DescricaoCurta {
            get {
                return ResourceManager.GetString("DescricaoCurta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição Longa.
        /// </summary>
        public static string DescricaoLonga {
            get {
                return ResourceManager.GetString("DescricaoLonga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horário.
        /// </summary>
        public static string HoraValidade {
            get {
                return ResourceManager.GetString("HoraValidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteúdo.
        /// </summary>
        public static string IdConteudo {
            get {
                return ResourceManager.GetString("IdConteudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteúdo Chave.
        /// </summary>
        public static string IdConteudoChave {
            get {
                return ResourceManager.GetString("IdConteudoChave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        public static string IdGrupoUsuario {
            get {
                return ResourceManager.GetString("IdGrupoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lançamento.
        /// </summary>
        public static string Lancamento {
            get {
                return ResourceManager.GetString("Lancamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova senha.
        /// </summary>
        public static string NovaSenha {
            get {
                return ResourceManager.GetString("NovaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observação.
        /// </summary>
        public static string Observacao {
            get {
                return ResourceManager.GetString("Observacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade.
        /// </summary>
        public static string Quantidade {
            get {
                return ResourceManager.GetString("Quantidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Senha {
            get {
                return ResourceManager.GetString("Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha atual.
        /// </summary>
        public static string SenhaAtual {
            get {
                return ResourceManager.GetString("SenhaAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servidor.
        /// </summary>
        public static string Servidor {
            get {
                return ResourceManager.GetString("Servidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL.
        /// </summary>
        public static string Ssl {
            get {
                return ResourceManager.GetString("Ssl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
    }
}
