//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagemResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagemResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Admin.Resources.MensagemResource", typeof(MensagemResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo não enviado!.
        /// </summary>
        public static string ArquivoNaoEnviado {
            get {
                return ResourceManager.GetString("ArquivoNaoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe uma data valida..
        /// </summary>
        public static string DataLimiteNpsInvalida {
            get {
                return ResourceManager.GetString("DataLimiteNpsInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro foi desativado com sucesso!.
        /// </summary>
        public static string DesativarSucesso {
            get {
                return ResourceManager.GetString("DesativarSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail não informado!.
        /// </summary>
        public static string EmailNaoInformado {
            get {
                return ResourceManager.GetString("EmailNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail foi enviado com sucesso!.
        /// </summary>
        public static string EmailSucesso {
            get {
                return ResourceManager.GetString("EmailSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível processar sua solicitação, ocorreu um erro!.
        /// </summary>
        public static string Erro {
            get {
                return ResourceManager.GetString("Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível processar sua solicitação, existem registros vinculados a este!.
        /// </summary>
        public static string ErroRelacionamento {
            get {
                return ResourceManager.GetString("ErroRelacionamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro foi excluído com sucesso!.
        /// </summary>
        public static string ExcluirSucesso {
            get {
                return ResourceManager.GetString("ExcluirSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato do arquivo não é aceito!.
        /// </summary>
        public static string FormatoNaoAceito {
            get {
                return ResourceManager.GetString("FormatoNaoAceito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem não informada!.
        /// </summary>
        public static string ImagemNaoInformada {
            get {
                return ResourceManager.GetString("ImagemNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, preencha o formulário corretamente!.
        /// </summary>
        public static string ModelStateInvalido {
            get {
                return ResourceManager.GetString("ModelStateInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum registro foi selecionado!.
        /// </summary>
        public static string NenhumRegistroSelecionado {
            get {
                return ResourceManager.GetString("NenhumRegistroSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uma nova senha foi envidada para o seu e-mail. Obrigado!.
        /// </summary>
        public static string RecuperarSenhaSucesso {
            get {
                return ResourceManager.GetString("RecuperarSenhaSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua senha foi alterada com sucesso!.
        /// </summary>
        public static string SenhaAlteradaSucesso {
            get {
                return ResourceManager.GetString("SenhaAlteradaSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro salvo com sucesso!.
        /// </summary>
        public static string Sucesso {
            get {
                return ResourceManager.GetString("Sucesso", resourceCulture);
            }
        }
    }
}
