//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagemResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagemResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shop.Resources.MensagemResource", typeof(MensagemResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O arquivo não foi enviado para o servidor!.
        /// </summary>
        public static string ArquivoNaoEnviado {
            get {
                return ResourceManager.GetString("ArquivoNaoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bem-vindo {0}!.
        /// </summary>
        public static string BemVindo {
            get {
                return ResourceManager.GetString("BemVindo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato do CEP é inválido..
        /// </summary>
        public static string CepInvalido {
            get {
                return ResourceManager.GetString("CepInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo importado com sucesso!.
        /// </summary>
        public static string DadosViagemSucesso {
            get {
                return ResourceManager.GetString("DadosViagemSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo validado com sucesso!.
        /// </summary>
        public static string DadosViagemValidado {
            get {
                return ResourceManager.GetString("DadosViagemValidado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro foi desativado com sucesso!.
        /// </summary>
        public static string DesativarSucesso {
            get {
                return ResourceManager.GetString("DesativarSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail foi enviado com sucesso!.
        /// </summary>
        public static string EmailSucesso {
            get {
                return ResourceManager.GetString("EmailSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail teste inválido!.
        /// </summary>
        public static string EmailTesteInvalido {
            get {
                return ResourceManager.GetString("EmailTesteInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O relatório foi emitido com sucesso!.
        /// </summary>
        public static string EmissaoRelatorioSucesso {
            get {
                return ResourceManager.GetString("EmissaoRelatorioSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível processar sua solicitação, ocorreu um erro!.
        /// </summary>
        public static string Erro {
            get {
                return ResourceManager.GetString("Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível processar sua solicitação, existem registros vinculados a este!.
        /// </summary>
        public static string ErroRelacionamento {
            get {
                return ResourceManager.GetString("ErroRelacionamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estorno foi efetuado com sucesso!.
        /// </summary>
        public static string EstornoEfetuadoSucesso {
            get {
                return ResourceManager.GetString("EstornoEfetuadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O relatório foi excluído com sucesso!.
        /// </summary>
        public static string ExcluirRelatorioSucesso {
            get {
                return ResourceManager.GetString("ExcluirRelatorioSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro foi excluído com sucesso!.
        /// </summary>
        public static string ExcluirSucesso {
            get {
                return ResourceManager.GetString("ExcluirSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato do arquivo não é aceito!.
        /// </summary>
        public static string FormatoNaoAceito {
            get {
                return ResourceManager.GetString("FormatoNaoAceito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, preencha o formulário corretamente!.
        /// </summary>
        public static string ModelStateInvalido {
            get {
                return ResourceManager.GetString("ModelStateInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível movimentar o estoque. Tente novamente!.
        /// </summary>
        public static string MovimentarEstoqueErro {
            get {
                return ResourceManager.GetString("MovimentarEstoqueErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Estoque foi movimentado com sucesso!.
        /// </summary>
        public static string MovimentarEstoqueSucesso {
            get {
                return ResourceManager.GetString("MovimentarEstoqueSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum registro foi selecionado!.
        /// </summary>
        public static string NenhumRegistroSelecionado {
            get {
                return ResourceManager.GetString("NenhumRegistroSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O prazo para preenchimento do formulário foi alterado com sucesso!.
        /// </summary>
        public static string PrazoPreenchimentoSucesso {
            get {
                return ResourceManager.GetString("PrazoPreenchimentoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uma nova senha foi envidada para o seu e-mail. Obrigado!.
        /// </summary>
        public static string RecuperarSenhaSucesso {
            get {
                return ResourceManager.GetString("RecuperarSenhaSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua senha foi alterada com sucesso!.
        /// </summary>
        public static string SenhaAlteradaSucesso {
            get {
                return ResourceManager.GetString("SenhaAlteradaSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O seu relatório foi enviado para emissão, aguarde até o termino do processo!.
        /// </summary>
        public static string SolicitacaoEmissaoRelatorioSucesso {
            get {
                return ResourceManager.GetString("SolicitacaoEmissaoRelatorioSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro salvo com sucesso!.
        /// </summary>
        public static string Sucesso {
            get {
                return ResourceManager.GetString("Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estorno foi realizado com sucesso!.
        /// </summary>
        public static string SucessoEstorno {
            get {
                return ResourceManager.GetString("SucessoEstorno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua mensagem foi enviada com sucesso. Obrigado!.
        /// </summary>
        public static string SucessoFaleConosco {
            get {
                return ResourceManager.GetString("SucessoFaleConosco", resourceCulture);
            }
        }
    }
}
